import { AppLanguage } from '../types';

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  ms: {
    // General / Headers
    'app.title': 'Pendamping Kalendar Dual',
    'app.subtitle': 'Keselarasan Putaran Matahari & Bulan',
    'app.desc': 'Terokai keselarasan matematik cakerawala. Tukar tarikh dengan ketepatan astronomi, semak perbandingan umur, dan jejaki kedudukan fasa bulan masa nyata.',
    'app.syncState': 'Status Segerak',
    'app.liveSystem': 'Penyegerakan Sistem Masa Nyata',
    'app.gregorianCycle': 'Kitaran Gregorian (Suria)',
    'app.hijriCycle': 'Kitaran Hijri (Qamari)',
    'app.gregorianDesc': 'Pengiraan orbit tropika (365.24 hari)',
    'app.hijriDesc': 'Kiraan fasa bulan astronomi',
    'app.coordinateDesc': 'Keselarasan koordinat dinamik dijana secara masa nyata.',
    'app.toggleNight': 'Tukar Mod Malam',
    
    // Tabs
    'tab.calendar': 'Kalendar Dual',
    'tab.tools': 'Penukar & Umur',
    'tab.events': 'Detik Bersejarah',
    'tab.reference': 'Info Sistem',

    // Calendar Selector
    'selector.title': 'Konfigurasi Enjin Kalendar',
    'selector.subtitle': 'Pilih kaedah perkiraan untuk menentukur rujukan masa lunar',
    'selector.offsetLabel': 'Pelarasan Manual (Hari)',
    'selector.offsetHelp': 'Laraskan jika penglihatan anak bulan tempatan berbeza 1 atau 2 hari berbanding perkiraan astronomi sains.',
    'selector.umalqura.name': 'Umm al-Qura (Arab Saudi)',
    'selector.umalqura.desc': 'Pengiraan astronomi yang dioptimumkan untuk kawasan Teluk & Saudi moden. Sangat penting bagi ketepatan semasa.',
    'selector.jakim.name': 'JAKIM Malaysia (MABIMS)',
    'selector.jakim.desc': 'Ditentukur mengikut kriteria kenampakan anak bulan JAKIM & serantau MABIMS (Ketinggian ≥ 3°, Elongasi ≥ 6.4°).',
    'selector.civil.name': 'Sivil Islam (Tabular)',
    'selector.civil.desc': 'Kalendar tabular klasik berasaskan matematik purba bermula epoch Jumaat. Cemerlang untuk rujukan sivil bertulis lama.',
    'selector.tbla.name': 'Tabular Klasik (Tbla)',
    'selector.tbla.desc': 'Sistem perkiraan aritmetik tradisional berasaskan epoch Khamis. Sering digunakan dalam manuskrip sejarah.',

    // Months (Hijri in Malay)
    'month.h1': 'Muharram',
    'month.h2': 'Safar',
    'month.h3': 'Rabiulawal',
    'month.h4': 'Rabiulakhir',
    'month.h5': 'Jamadilawal',
    'month.h6': 'Jamadilakhir',
    'month.h7': 'Rajab',
    'month.h8': 'Syaaban',
    'month.h9': 'Ramadan',
    'month.h10': 'Syawal',
    'month.h11': 'Zulkaedah',
    'month.h12': 'Zulhijjah',

    // Months (Gregorian in Malay)
    'month.g1': 'Januari',
    'month.g2': 'Februari',
    'month.g3': 'Mac',
    'month.g4': 'April',
    'month.g5': 'Mei',
    'month.g6': 'Jun',
    'month.g7': 'Julai',
    'month.g8': 'Ogos',
    'month.g9': 'September',
    'month.g10': 'Oktober',
    'month.g11': 'November',
    'month.g12': 'Disember',

    // Days (Malay)
    'day.sunday': 'Ahad',
    'day.monday': 'Isnin',
    'day.tuesday': 'Selasa',
    'day.wednesday': 'Rabu',
    'day.thursday': 'Khamis',
    'day.friday': 'Jumaat',
    'day.saturday': 'Sabtu',

    // Dual Calendar Component
    'cal.gregorianHeader': 'Kalendar Gregorian',
    'cal.hijriHeader': 'Kalendar Hijri',
    'cal.syncView': 'Paparan Segerak',
    'cal.legendToday': 'Hari Ini',
    'cal.legendSelected': 'Dipilih',
    'cal.prevMonth': 'Bulan Sebelumnya',
    'cal.nextMonth': 'Bulan Seterusnya',
    'cal.noEvents': 'Tiada peristiwa untuk hari ini',
    'cal.selectDayPrompt': 'Pilih mana-mana kotak tarikh untuk melihat perincian silang kalendar.',

    // Age Calculator
    'age.title': 'Penganalisis Umur Bandingan',
    'age.desc': 'Bandingkan jurang perjalanan hayat anda di bawah sistem solar matahari dan lunar bulan.',
    'age.birthLabel': 'Tarikh Lahir (Gregorian)',
    'age.targetLabel': 'Tarikh Pengiraan (Lalai Hari Ini)',
    'age.calculateBtn': 'Mula Kira Perbezaan Umur',
    'age.gregorianResult': 'Umur Kitaran Gregorian',
    'age.hijriResult': 'Umur Kitaran Hijri',
    'age.years': 'Tahun',
    'age.months': 'Bulan',
    'age.days': 'Hari',
    'age.totalDays': 'Jumlah Terkumpul',
    'age.daysLower': 'hari',
    'age.nextBirthday': 'Hari Lahir Seterusnya',
    'age.remaining': 'baki',
    'age.milestoneNotice': 'Kerana tahun Hijri ~11 hari lebih pendek daripada Gregorian, umur Hijri anda sentiasa bertambah lebih cepat!',

    // Date Converter
    'conv.title': 'Penukar Tarikh Persis',
    'conv.desc': 'Tukar tarikh secara dua hala antara sistem Gregorian dan Hijri menggunakan algoritma persis seketika.',
    'conv.direction': 'Arah Penukaran',
    'conv.gToH': 'Gregorian kepada Hijri (Solar -> Lunar)',
    'conv.hToG': 'Hijri kepada Gregorian (Lunar -> Solar)',
    'conv.selectG': 'Pilih Tarikh Gregorian',
    'conv.enterH': 'Masukkan Tarikh Hijri',
    'conv.year': 'Tahun',
    'conv.month': 'Bulan',
    'conv.day': 'Hari',
    'conv.convertBtn': 'Laksanakan Penukaran',
    'conv.result': 'Hasil Penukaran Ditentukur',
    'conv.invalidDate': 'Sila masukkan nombor tarikh yang sah!',

    // Lunar Phase
    'moon.title': 'Fasa Bulan Hari Ini',
    'moon.desc': 'Illuminasi fizikal relatif anak bulan pada kitaran lunar semasa.',
    'moon.illumination': 'Kadar Pencahayaan',
    'moon.phase': 'Nama Fasa',
    'moon.new': 'Anak Bulan (Hilal Awal)',
    'moon.wax_crescent': 'Bulan Sabit Wari (Hilal)',
    'moon.first_quarter': 'Suku Pertama (Tarbi\')',
    'moon.wax_gibbous': 'Bulan Hampir Purnama',
    'moon.full': 'Bulan Purnama (Badr)',
    'moon.wan_gibbous': 'Bulan Susut Suku',
    'moon.third_quarter': 'Suku Akhir (Tarbi\' Thani)',
    'moon.wan_crescent': 'Bulan Sabit Akhir',

    // Milestones (IslamicEventsCountdown)
    'events.title': 'Detik Peristiwa Islam & Fasa Sunat',
    'events.desc': 'Semak anggaran tarikh bagi perayaan Islam serta tarikh digalakkan berpuasa sunat bagi tahun semasa.',
    'events.searchPlaceholder': 'Tapis nama peristiwa...',
    'events.fastingCat': 'Amalan Puasa Sunat',
    'events.majorCat': 'Hari Kebesaran Islam',
    'events.daysLeft': 'hari lagi',
    'events.today': 'Hari ini!',
    'events.occurred': 'Sudah berlalu',
    'events.hijriDateLabel': 'Tarikh Hijri',
    'events.gregDateLabel': 'Anggaran Gregorian',

    // Event names
    'event.ramadan': 'Awal Ramadan (Puasa Wajib)',
    'event.eid_fitr': 'Hari Raya Aidilfitri',
    'event.eid_adha': 'Hari Raya Aidiladha',
    'event.muharram': 'Awal Muharram (Tahun Baru Hijri)',
    'event.ashura': 'Hari Asyura (10 Muharram)',
    'event.tasua': 'Hari Tasu\'a (9 Muharram)',
    'event.maulid': 'Maulidur Rasul (Keputeraan Nabi)',
    'event.isra_miraj': 'Isra\' dan Mi\'raj',
    'event.nisfu': 'Malam Nisfu Syaaban',
    'event.arafah': 'Hari Arafah (9 Zulhijjah)',
    'event.ayyam_beidh_7': 'Puasa Ayyamul Bidh (Rejab)',
    'event.ayyam_beidh_8': 'Puasa Ayyamul Bidh (Syaaban)',
    'event.ayyam_beidh_10': 'Puasa Ayyamul Bidh (Syawal)',
    'event.ayyam_beidh_11': 'Puasa Ayyamul Bidh (Zulkaedah)',
    'event.ayyam_beidh_12': 'Puasa Ayyamul Bidh (Zulhijjah)',
    'event.ayyam_beidh_1': 'Puasa Ayyamul Bidh (Muharram)',
    'event.ayyam_beidh_2': 'Puasa Ayyamul Bidh (Safar)',
    'event.ayyam_beidh_3': 'Puasa Ayyamul Bidh (Rabiulawal)',
    'event.ayyam_beidh_4': 'Puasa Ayyamul Bidh (Rabiulakhir)',
    'event.ayyam_beidh_5': 'Puasa Ayyamul Bidh (Jamadilawal)',
    'event.ayyam_beidh_6': 'Puasa Ayyamul Bidh (Jamadilakhir)',
    'event.six_syawal': 'Puasa Enam Syawal',

    // Educational / Glossary
    'edu.title': 'Kamus & Pengetahuan Astronomi Islam',
    'edu.desc': 'Fahami asas matematik, kaedah kenampakan anak bulan, dan sejarah keindahan pembinaan kalendar lunar.',
    'edu.q1': 'Mengapa wujud perbezaan versi kalendar Hijri?',
    'edu.a1': 'Sistem Umm al-Qura menggunakan kriteria astronomi pra-kiraan di koordinat Makkah. Manakala JAKIM Malaysia mematuhi kriteria baharu MABIMS yang memerlukan ukuran altitud bulan ≥ 3° dan elongasi ≥ 6.4° ketika matahari terbenam untuk meluluskan rukyah harian. Kalendar Tabular pula menggunakan formula matematik tetap tanpa menghiraukan kedudukan fizikal anak bulan.',
    'edu.q2': 'Apakah kepentingan fasa Ayyamul Bidh?',
    'edu.a2': 'Ayyamul Bidh bermaksud "Hari-hari Putih", merujuk kepada malam ke-13, 14, dan 15 setiap bulan Hijri di mana bulan berada paling penuh dan terang (Purnama). Umat Islam amat digalakkan melakukan puasa sunat pada hari-hari ini.',
    'edu.q3': 'Mengapa umur Hijri bertambah lebih cepat?',
    'edu.a3': 'Kalendar lunar berpandukan kitaran bulan sebanyak 354 atau 355 hari setahun, manakala kalendar solar Gregorian berpandukan pusingan matahari sebanyak 365 atau 366 hari. Perbezaan ~11 hari setahun ini menyebabkan umur Hijri anda mendahului umur Gregorian sebanyak kira-kira 1 tahun pada setiap kitaran 33 tahun solar.',
  },
  en: {
    // General / Headers
    'app.title': 'Dual Calendar Companion',
    'app.subtitle': 'Solar & Lunar Temporal Harmony',
    'app.desc': 'Examine the celestial mathematical alignments. Convert days with astronomical precision, check comparative age parameters, and track real-time moon phase coordinates.',
    'app.syncState': 'Sync State',
    'app.liveSystem': 'Live System Synchronicity',
    'app.gregorianCycle': 'Gregorian Cycle (Solar)',
    'app.hijriCycle': 'Hijri Cycle (Lunar)',
    'app.gregorianDesc': 'Tropical orbital calculation (365.24 days)',
    'app.hijriDesc': 'Astronomical lunar phase computation',
    'app.coordinateDesc': 'Dynamic coordinate alignment powered by client-side calculations.',
    'app.toggleNight': 'Toggle Night Mode',

    // Tabs
    'tab.calendar': 'Dual Calendar',
    'tab.tools': 'Penukt & Age',
    'tab.events': 'Milestones',
    'tab.reference': 'System Info',

    // Calendar Selector
    'selector.title': 'Calendar Engine Configuration',
    'selector.subtitle': 'Select computation rules to calibrate lunar temporal coordinates',
    'selector.offsetLabel': 'Manual Adjustment (Days)',
    'selector.offsetHelp': 'Compensate if actual local crescent sightings differ 1 or 2 days from international scientific computations.',
    'selector.umalqura.name': 'Umm al-Qura (Saudi Arabia)',
    'selector.umalqura.desc': 'Astronomical calculations optimized for modern Saudi & Gulf region sightings. Essential for contemporary accuracy.',
    'selector.jakim.name': 'JAKIM Malaysia (MABIMS)',
    'selector.jakim.desc': 'Calibrated to Jabatan Kemajuan Islam Malaysia and MABIMS regional sighting criteria (Altitude ≥ 3°, Elongation ≥ 6.4°).',
    'selector.civil.name': 'Islamic Civil (Tabular)',
    'selector.civil.desc': 'Classically computed tabular calendar utilizing a Friday epoch. Excellent for historical records.',
    'selector.tbla.name': 'Classical Tabular (Tbla)',
    'selector.tbla.desc': 'Traditional arithmetic computation based on a Thursday epoch. Frequently found in historic manuscripts.',

    // Months (Hijri in English)
    'month.h1': 'Muharram',
    'month.h2': 'Safar',
    'month.h3': "Rabi' al-Awwal",
    'month.h4': "Rabi' ath-Thani",
    'month.h5': 'Jumada al-Ula',
    'month.h6': 'Jumada al-Akhirah',
    'month.h7': 'Rajab',
    'month.h8': "Sha'ban",
    'month.h9': 'Ramadan',
    'month.h10': 'Shawwal',
    'month.h11': 'Dhu al-Qadah',
    'month.h12': 'Dhu al-Hijjah',

    // Months (Gregorian in English)
    'month.g1': 'January',
    'month.g2': 'February',
    'month.g3': 'March',
    'month.g4': 'April',
    'month.g5': 'May',
    'month.g6': 'June',
    'month.g7': 'July',
    'month.g8': 'August',
    'month.g9': 'September',
    'month.g10': 'October',
    'month.g11': 'November',
    'month.g12': 'December',

    // Days (English)
    'day.sunday': 'Sunday',
    'day.monday': 'Monday',
    'day.tuesday': 'Tuesday',
    'day.wednesday': 'Wednesday',
    'day.thursday': 'Thursday',
    'day.friday': 'Friday',
    'day.saturday': 'Saturday',

    // Dual Calendar Component
    'cal.gregorianHeader': 'Gregorian Calendar',
    'cal.hijriHeader': 'Hijri Calendar',
    'cal.syncView': 'Synchronized Grid',
    'cal.legendToday': 'Today',
    'cal.legendSelected': 'Selected',
    'cal.prevMonth': 'Prev Month',
    'cal.nextMonth': 'Next Month',
    'cal.noEvents': 'No islamic milestones today',
    'cal.selectDayPrompt': 'Click any cell grid option above to examine cross-calendar temporal alignments.',

    // Age Calculator
    'age.title': 'Comparative Age Analyzer',
    'age.desc': 'Determine your exact life cycle intervals as computed under solar and lunar timelines.',
    'age.birthLabel': 'Birth Date (Gregorian)',
    'age.targetLabel': 'Target Date (Defaults to Today)',
    'age.calculateBtn': 'Process Chronometrics',
    'age.gregorianResult': 'Solar (Gregorian) Lifecycle',
    'age.hijriResult': 'Lunar (Hijri) Lifecycle',
    'age.years': 'Years',
    'age.months': 'Months',
    'age.days': 'Days',
    'age.totalDays': 'Accumulated Sum',
    'age.daysLower': 'days',
    'age.nextBirthday': 'Next Birthday',
    'age.remaining': 'remaining',
    'age.milestoneNotice': 'Since the lunar year is ~11 days shorter than Gregorian, your Hijri age increments faster!',

    // Date Converter
    'conv.title': 'Dual Date Converter',
    'conv.desc': 'Instantly translate dates bidirectionally between solar Gregorian and lunar Hijri systems.',
    'conv.direction': 'Conversion Mode',
    'conv.gToH': 'Gregorian to Hijri (Solar -> Lunar)',
    'conv.hToG': 'Hijri to Gregorian (Lunar -> Solar)',
    'conv.selectG': 'Select Gregorian Date',
    'conv.enterH': 'Enter Hijri Coordinates',
    'conv.year': 'Year',
    'conv.month': 'Month',
    'conv.day': 'Day',
    'conv.convertBtn': 'Process Conversion',
    'conv.result': 'Calibrated Output Result',
    'conv.invalidDate': 'Please enter acceptable dates!',

    // Lunar Phase
    'moon.title': "Today's Moon Phase",
    'moon.desc': 'Calculated physical lunar appearance based on current Hijri month cycle coordinate.',
    'moon.illumination': 'Illumination Rating',
    'moon.phase': 'Scientific Phase',
    'moon.new': 'New Moon (Hilal)',
    'moon.wax_crescent': 'Waxing Crescent',
    'moon.first_quarter': 'First Quarter (Tarbi\')',
    'moon.wax_gibbous': 'Waxing Gibbous',
    'moon.full': 'Full Moon (Badr)',
    'moon.wan_gibbous': 'Waning Gibbous',
    'moon.third_quarter': 'Third Quarter (Tarbi\' Thani)',
    'moon.wan_crescent': 'Waning Crescent',

    // Milestones (IslamicEventsCountdown)
    'events.title': 'Islamic Holy Milestones & Fasting Schedule',
    'events.desc': 'View expected dates for festive events and highly encouraged optional fasting days during this year.',
    'events.searchPlaceholder': 'Filter milestones...',
    'events.fastingCat': 'Encouraged Voluntary Fasting',
    'events.majorCat': 'Major Festivities & Holidays',
    'events.daysLeft': 'days left',
    'events.today': 'Today!',
    'events.occurred': 'Already occurred',
    'events.hijriDateLabel': 'Hijri Date',
    'events.gregDateLabel': 'Estimated Solar Date',

    // Event names
    'event.ramadan': 'Awwal Ramadan (Obligatory Fasting)',
    'event.eid_fitr': 'Eid al-Fitr (Festival of Fast-Breaking)',
    'event.eid_adha': 'Eid al-Adha (Festival of Sacrifice)',
    'event.muharram': "Awwal Muharram (Hijri New Year's Day)",
    'event.ashura': 'Day of Ashura (10th Muharram)',
    'event.tasua': "Day of Tasu'a (9th Muharram)",
    'event.maulid': 'Mawlid an-Nabi (Prophet’s Birthday)',
    'event.isra_miraj': "Al-Isra' wal-Mi'raj",
    'event.nisfu': "Nisfu Sha'ban Night",
    'event.arafah': 'Day of Arafah (9th Dhu al-Hijjah)',
    'event.ayyam_beidh_7': 'Ayyam al-Beidh Fasting (Rajab)',
    'event.ayyam_beidh_8': "Ayyam al-Beidh Fasting (Sha'ban)",
    'event.ayyam_beidh_10': 'Ayyam al-Beidh Fasting (Shawwal)',
    'event.ayyam_beidh_11': 'Ayyam al-Beidh Fasting (Dhu al-Qadah)',
    'event.ayyam_beidh_12': 'Ayyam al-Beidh Fasting (Dhu al-Hijjah)',
    'event.ayyam_beidh_1': 'Ayyam al-Beidh Fasting (Muharram)',
    'event.ayyam_beidh_2': 'Ayyam al-Beidh Fasting (Safar)',
    'event.ayyam_beidh_3': "Ayyam al-Beidh Fasting (Rabi' I)",
    'event.ayyam_beidh_4': "Ayyam al-Beidh Fasting (Rabi' II)",
    'event.ayyam_beidh_5': 'Ayyam al-Beidh Fasting (Jumada I)',
    'event.ayyam_beidh_6': 'Ayyam al-Beidh Fasting (Jumada II)',
    'event.six_syawal': 'Six Day Fasting of Shawwal',

    // Educational / Glossary
    'edu.title': 'Islamic Astronomical Glossary & Knowledge Hub',
    'edu.desc': 'Familiarize yourself with mathematical mechanics, lunar crescent criteria, and the historical engineering of the Islamic calendar.',
    'edu.q1': 'What is the structural difference in Hijri engines?',
    'edu.a1': 'Saudi Arabia’s Umm al-Qura system computes astronomical predictions referencing coordinates in Makkah. Malaysia’s JAKIM strictly applies updated MABIMS regional sighting criteria (Altitude ≥ 3° and Elongation ≥ 6.4° at sunset) to officially validate monthly starts. Classical Islamic Civil (Tabular) uses standard mathematically fixed alternations ignoring physical crescent positions.',
    'edu.q2': 'What is the significance of Ayyamul Bidh days?',
    'edu.a2': 'Ayyamul Bidh literally translates to "The White Days", referring specifically to the 13th, 14th, and 15th nights of each Hijri month. During these evenings, the moon shines bright at peak reflection (Full Moon). Voluntary fasting is recommended during these three intermediate dates.',
    'edu.q3': 'Why do lunar age counts speed ahead?',
    'edu.a3': 'A lunar year comprises approximately 354 or 355 days, while a Gregorian solar year tracks approximately 365 or 366 days. This negative variance of about 11 days annually ensures your lunar age exceeds Gregorian age by roughly 1 whole year over every 33 solar years.',
  },
  ar: {
    // General / Headers
    'app.title': 'رفيق التقويم المزدوج',
    'app.subtitle': 'الانسجام الزمني الشمسي والقمري',
    'app.desc': 'استكشف التوافق الرياضي الفلكي المنظم. حوّل التواريخ بذكاء فائق ودقة فلكية متناهية، وافحص معايير العمر المقارن، وتابع تضاريس إشعاع القمر الزمني.',
    'app.syncState': 'حالة المزامنة',
    'app.liveSystem': 'مزامنة النظام في الوقت الفعلي',
    'app.gregorianCycle': 'الدورة الميلادية (شمسية)',
    'app.hijriCycle': 'الدورة الهجرية (قمرية)',
    'app.gregorianDesc': 'الحساب المداري الاستوائي (٣٦٥.٢٤ يوماً)',
    'app.hijriDesc': 'حساب التطور القمري وحركة الأهلة الفلكية',
    'app.coordinateDesc': 'توافق إحداثي تفاعلي مدعوم بحسابات النظم المحلية بالمتصفح.',
    'app.toggleNight': 'تبديل الوضع الليلي',

    // Tabs
    'tab.calendar': 'التقويم المزدوج',
    'tab.tools': 'المحولات والعمر',
    'tab.events': 'المناسبات والذكريات',
    'tab.reference': 'معلومات النظام',

    // Calendar Selector
    'selector.title': 'إعدادات محرك التقويم والضبط',
    'selector.subtitle': 'اختر آلية الحساب المعتمدة لمعايرة التوقيت الهجري القمري بدقة',
    'selector.offsetLabel': 'التعديل العشري اليدوي (أيام)',
    'selector.offsetHelp': 'قم بمواءمة الإشارات الفلكية في حال اختلف إثبات رؤية الهلال المحلي بمقدار يوم أو يومين عن المحاسبات النظرية.',
    'selector.umalqura.name': 'تقويم أم القرى (المملكة العربية السعودية)',
    'selector.umalqura.desc': 'تقديرات وحسابات فلكية معمقة معتمدة في مكة المكرمة والمناطق المجاورة. أساسية لضبط الوقائع والعبادات.',
    'selector.jakim.name': 'جاكيم ماليزيا (مابيمس)',
    'selector.jakim.desc': 'معاير طبقاً لمعايير الرؤية الإقليمية لمجلس مابيمس (ارتفاع الهلال ≥ ٣ درجات، الاستطالة ≥ ٦.٤ درجة عند الغروب).',
    'selector.civil.name': 'التقويم المدني الإسلامي (صطلاحي)',
    'selector.civil.desc': 'تقويم حسابي كلاسيكي منتظم يعتمد على عهد يوم الجمعة. مفيد للوثائق والمراجع التاريخية والمدنية العتيقة.',
    'selector.tbla.name': 'الحساب التقويمي الكلاسيكي (طبولتي)',
    'selector.tbla.desc': 'تعديل حسابي كلاسيكي تقليدي مبني على عهد يوم الخميس. واسع الاستعمال في المخطوطات القديمة.',

    // Months (Arabic)
    'month.h1': 'المحرّم',
    'month.h2': 'صفر',
    'month.h3': 'ربيع الأول',
    'month.h4': 'ربيع الثاني',
    'month.h5': 'جمادى الأولى',
    'month.h6': 'جمادى الآخرة',
    'month.h7': 'رجب',
    'month.h8': 'شعبان',
    'month.h9': 'رمضان',
    'month.h10': 'شوال',
    'month.h11': 'ذو القعدة',
    'month.h12': 'ذو الحجة',

    // Months (Gregorian Arabic)
    'month.g1': 'يناير',
    'month.g2': 'فبراير',
    'month.g3': 'مارس',
    'month.g4': 'أبريل',
    'month.g5': 'مايو',
    'month.g6': 'يونيو',
    'month.g7': 'يوليو',
    'month.g8': 'أغسطس',
    'month.g9': 'سبتمبر',
    'month.g10': 'أكتوبر',
    'month.g11': 'نوفمبر',
    'month.g12': 'ديسمبر',

    // Days (Arabic)
    'day.sunday': 'الأحد',
    'day.monday': 'الإثنين',
    'day.tuesday': 'الثلاثاء',
    'day.wednesday': 'الأربعاء',
    'day.thursday': 'الخميس',
    'day.friday': 'الجمعة',
    'day.saturday': 'السبت',

    // Dual Calendar Component
    'cal.gregorianHeader': 'التقويم الميلادي',
    'cal.hijriHeader': 'التقويم الهجري',
    'cal.syncView': 'العرض التزامني المترابط',
    'cal.legendToday': 'اليوم',
    'cal.legendSelected': 'المعاين',
    'cal.prevMonth': 'الشهر السابق',
    'cal.nextMonth': 'الشهر التالي',
    'cal.noEvents': 'لا ذكريات هجرية أو وطنية مسجلة هذا اليوم',
    'cal.selectDayPrompt': 'انقر على خانة يوم محدد في الشبكة لمطابقة الفترات وتفصيل التقاء الدورتين زمانياً.',

    // Age Calculator
    'age.title': 'مقياس الفجوة وحساب العمر المقارن',
    'age.desc': 'تعرّف على السنين والشهور التي قضيتها في رحلتك الحياتية مفصلة بالدورتين الشمسية والقمرية.',
    'age.birthLabel': 'تاريخ الميلاد الميلادي',
    'age.targetLabel': 'التاريخ المطلوب (تلقائياً تاريخ اليوم)',
    'age.calculateBtn': 'شروع في معالجة وتحليل العمر القياسي',
    'age.gregorianResult': 'حياتك بالدورة الميلادية (الشمسية)',
    'age.hijriResult': 'حياتك بالدورة الهجرية (القمرية)',
    'age.years': 'سنة',
    'age.months': 'شعر',
    'age.days': 'يوم',
    'age.totalDays': 'رصيدك الإجمالي بالأيام',
    'age.daysLower': 'يوماً',
    'age.nextBirthday': 'الذكرى القادمة لميلادك',
    'age.remaining': 'متبقي',
    'age.milestoneNotice': 'بما أن السنة القمرية أقصر من الشمسية بقرابة ١١ يوماً، فإن عمرك بالتقويم الهجري يزيد ويسير أسرع دائماً!',

    // Date Converter
    'conv.title': 'محول التواريخ التفاعلي',
    'conv.desc': 'حوّل التواريخ بمرونة تامة وبشكل ثنائي الاتجاه بين نظامي الجريان الشمسي والقمري بدقة رياضية مرصوصة.',
    'conv.direction': 'اتجاه التحويل المباشر',
    'conv.gToH': 'من الميلادي إلى الهجري (شمسي -> قمري)',
    'conv.hToG': 'من الهجري إلى الميلادي (قمري -> شمسي)',
    'conv.selectG': 'اختر التاريخ الميلادي',
    'conv.enterH': 'قم بإدخال المعطيات الهجرية',
    'conv.year': 'السنة',
    'conv.month': 'الشهر',
    'conv.day': 'اليوم',
    'conv.convertBtn': 'تطبيق معالجة التحويل',
    'conv.result': 'الناتج الموائم بعد المعايرة',
    'conv.invalidDate': 'برجاء تدوين قيم صحيحة ومقبولة للتواريخ!',

    // Lunar Phase
    'moon.title': 'تضاريس وهيئة القمر الحالية',
    'moon.desc': 'الشكل الإشعاعي ومقدار السطوع الفيزيائي المكتسب للقمر طبقاً للظرف الحالي من الشهر الهجري.',
    'moon.illumination': 'معدل السطوع والإنارة',
    'moon.phase': 'المظهر الفلكي العلمي',
    'moon.new': 'المحاق / الهلال الطالع',
    'moon.wax_crescent': 'الهلال المتزايد',
    'moon.first_quarter': 'التربيع الأول',
    'moon.wax_gibbous': 'الأحدب المتزايد',
    'moon.full': 'البدر الكامل',
    'moon.wan_gibbous': 'الأحدب المتناقص',
    'moon.third_quarter': 'التربيع الثاني',
    'moon.wan_crescent': 'الهلال المتناقص الخاتم',

    // Milestones (IslamicEventsCountdown)
    'events.title': 'شعائر العبادات والمناسبات الإسلامية العظمى',
    'events.desc': 'تتبع رصيد الأيام المتبقية والمواعيد المتوقعة السنوية للأعياد والمواسم والصلات والأيام البيض المباركة.',
    'events.searchPlaceholder': 'فلترة المناسبات والشعائر...',
    'events.fastingCat': 'أيام الصيام والعبادات المستحبة',
    'events.majorCat': 'المواسم والأعياد الإسلامية الكبرى',
    'events.daysLeft': 'يوم متبقي',
    'events.today': 'اليوم المحتفى به!',
    'events.occurred': 'مر وانقضى',
    'events.hijriDateLabel': 'الموعد الهجري المقدر',
    'events.gregDateLabel': 'المطابقة الشمسية التقريبية',

    // Event names
    'event.ramadan': 'غرة شهر رمضان المبارك (بداية الصيام)',
    'event.eid_fitr': 'عيد الفطر السعيد',
    'event.eid_adha': 'عيد الأضحى المبارك',
    'event.muharram': 'رأس السنة الهجرية الجديدة',
    'event.ashura': 'يوم عاشوراء (العاشر من محرم)',
    'event.tasua': 'يوم تاسوعاء (التاسع من محرم)',
    'event.maulid': 'المولد النبوي الشريف المعظم',
    'event.isra_miraj': 'ليلة الإسراء والمعراج المباركة',
    'event.nisfu': 'ليلة النصف من شعبان',
    'event.arafah': 'يوم عرفة المبارك (التاسع من ذي الحجة)',
    'event.ayyam_beidh_7': 'صيام الأيام البيض (رجب)',
    'event.ayyam_beidh_8': 'صيام الأيام البيض (شعبان)',
    'event.ayyam_beidh_10': 'صيام الأيام البيض (شوال)',
    'event.ayyam_beidh_11': 'صيام الأيام البيض (ذو القعدة)',
    'event.ayyam_beidh_12': 'صيام الأيام البيض (ذو الحجة)',
    'event.ayyam_beidh_1': 'صيام الأيام البيض (محرم)',
    'event.ayyam_beidh_2': 'صيام الأيام البيض (صفر)',
    'event.ayyam_beidh_3': 'صيام الأيام البيض (ربيع الأول)',
    'event.ayyam_beidh_4': 'صيام الأيام البيض (ربيع الثاني)',
    'event.ayyam_beidh_5': 'صيام الأيام البيض (جمادى الأولى)',
    'event.ayyam_beidh_6': 'صيام الأيام البيض (جمادى الآخرة)',
    'event.six_syawal': 'صيام الست من شوال (الست البيض)',

    // Educational / Glossary
    'edu.title': 'المصطلحات الفلكية والدليل المعرفي',
    'edu.desc': 'تعمق في الميكانيكا الرياضية وجذور صياغة التوقعات وتفاضل التقاويم المتوارثة عبر الزمن الإسلامي والعلمي.',
    'edu.q1': 'ما مبعث الاختلاف في نظم ومحركات التقويم الهجري؟',
    'edu.a1': 'يرتكز تقويم أم القرى السعودي على حسابات اصطلاحية تكميلية دقيقة مخصصة لإحداثيات مكة. بينما تعتمد ماليزيا عبر جاكيم شروطًا بصرية متطورة طبقاً لدول مابيمس الإقليمية (تتطلب سعة زاوية لا تقل عن ٦.٤ درجة وسمك ارتفاع لا يقل عن ٣ درجات لحظة غياب الشمس). بينما يصيغ الحساب الاصطلاحي المدني الهجري أرقاماً ثابتة متعاقبة مستقرة للتاريخ.',
    'edu.q2': 'ما المغزى النبوي والصحي لصيام الأيام البيض؟',
    'edu.a2': 'تُعرف بالأيام البيض نسبة إلى شهود لياليها الثالث عشر والرابع عشر والخامس عشر من الشهر القمري، حيث يتكامل غمد القمر سطوعاً وتألقاً (بدراً). يُسن ويُستحب صيامها طاعة ووقاية ومنافع صحية مثبتة للجسد تحت توقيت فورة الاندثار البدري.',
    'edu.q3': 'لماذا يزيد عمر الفرد طبقاً للرقم الهجري عن الميلادي؟',
    'edu.a3': 'تدور السنة القمرية قرابة ٣٥٤ أو ٣٥٥ يوماً، تاركة فارق عجز يقدر بـ ١١ يوماً سنوياً أمام العام الشمسي الميلادي (٣٦٥ أو ٣٦٦ يوماً). هذا النقص يسفر عن تحقيق تفوق سنة افتراضية كاملة للفرد على عمره الميلادي كلما استدار الزمن ٣٣ سنة شمسية كاملة.',
  }
};

export function getTranslation(key: string, lang: AppLanguage, fallback: string = ''): string {
  const dict = TRANSLATIONS[lang] || TRANSLATIONS['ms'];
  return dict[key] || fallback || key;
}
